'\" t

.TH "2absp" "1" "21\ \&MARCH\ \&2019" "2absp 1.0.0 - alpha" "2absp"

.SH "NAME"
2absp - converts file path to absolute path
.SH "SYNOPSIS"
\fB2absp\fR \fBpath_1\fR [\fBpath_2\fR... [\fBpath_n\fR]]
.SH "DESCRIPTION"
Converts file pathes to absolute. NOTE: 2absp \fBDOES NOT\fR check if pathes exist.
.PP
.SH "OPTIONS"
No options
.PP
.SH "EXAMPLES"
2absp ../../projects
.RS 4
Output absolute path to ../../projects
.RE
2absp ~/Documents/ Wallpapers/see/see-wallpaper03.png
.RS 4
Output absolute pathes to ~/Documents/ and ./Wallpapers/see/see-wallpaper03.png
.RE
.PP
.SH "AUTHOR"
Kuznetsov Leonid
.RS 4
https://github.com/kuznetsovlv
https://www.linkedin.com/in/kuznetsov-leonid-651a50126/
.RE
.SH "REPORTING BUGS"
https://github.com/kuznetsovlv/mwlc/issues
